language: ruby
rvm:
  - 2.0.0

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:migrate

script:
  - bundle exec rspec

addons:
  postgresql: "9.3"

services:
  - redis-server